import {sharedHorizon,chartGeometry,JOB_COLORS,JOB_TEXT_COLORS} from './chart-layout.mjs';
const $=id=>document.getElementById(id),n=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
let state=null,generation=0,mutationPending=false,previousProposal=null;
function setBusy(busy){for(const button of document.querySelectorAll('button'))button.disabled=busy;$('status').textContent=busy?'로컬 검토 응답을 기다리는 중…':'';if(!busy)decision();}
async function request(path,input){if(input&&mutationPending)return;const current=++generation;if(input){input={...input,...(['propose','import','calendar','reset'].includes(path)?{sourceFingerprint:state.sourceFingerprint}:{})};mutationPending=true;}setBusy(true);try{const response=await fetch('/api/'+path,input?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}:{});const result=await response.json();if(current!==generation)return;if(!response.ok){if(response.status===409){state=await(await fetch('/api/state')).json();render();}throw Error((result.message||result.error)+' · inspect again before confirming');}if(state&&result.version<state.version)return;state=result;$('status').textContent='';if(path==='import')$('import-status').textContent='기준 일정 적용 완료 · revision '+state.sourceRevision+' · '+state.baseline.status+' / '+state.baselineVerification.status;render();}catch(e){if(current===generation){$('status').textContent=e.message;if(path==='import')$('import-status').textContent=e.message;}}finally{if(input)mutationPending=false;if(current===generation){for(const button of document.querySelectorAll('button'))button.disabled=false;decision();}}}
const color=id=>Object.hasOwn(JOB_COLORS,id)?JOB_COLORS[id]:['#173f60','#237563','#765091','#386394'][Math.max(0,(state?.changed||state?.base)?.jobs.findIndex(job=>job.id===id)??0)%4];
const svg=(tag,attrs,text)=>{const e=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v]of Object.entries(attrs||{}))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;return e;};
function gantt(target,data,plan,horizon){const root=$(target);root.replaceChildren();if(!plan?.schedule?.length){root.append(n('div',plan?'No feasible incumbent · '+plan.status:'지원되는 변경의 해석을 확인하면 계획을 계산합니다','empty'));return;}const {width,height,left,right}=chartGeometry(horizon),w=Math.max(width,left+right+165+data.jobs.reduce((sum,job)=>sum+Math.max(75,job.id.length*8+40),0)),scale=(w-left-right)/horizon;const chart=svg('svg',{viewBox:'0 0 '+w+' '+height,width:w,height,role:'img','aria-label':'Machine schedule. Shared origin 0 to '+horizon+' minutes; half-open intervals.'});chart.style.width=w+'px';chart.style.minWidth=w+'px';
 for(let minute=0;minute<=horizon;minute+=Math.max(1,Math.ceil(horizon/60))){const x=left+minute*scale;chart.append(svg('line',{x1:x,y1:28,x2:x,y2:195,stroke:'#e7edf1'}),svg('text',{x,y:20,'text-anchor':'middle','font-size':14,fill:'#142635'},String(minute)));}
 for(const [i,machine]of data.machines.entries()){const y=55+i*76;chart.append(svg('text',{x:5,y:y+25,'font-size':14,fill:'#142635'},machine),svg('line',{x1:left,y1:y+43,x2:w-right,y2:y+43,stroke:'#9eaeba'}));for(const outage of data.outages.filter(o=>o.machine===machine)){const r=svg('rect',{x:left+outage.start*scale,y:y-7,width:(outage.end-outage.start)*scale,height:54,fill:'#e7edf1',stroke:'#566b7a','stroke-dasharray':'3 3'});r.append(svg('title',{},'Unavailable '+machine+' ['+outage.start+','+outage.end+')'));chart.append(r,svg('text',{x:left+(outage.start+outage.end)*scale/2,y:y+64,'text-anchor':'middle','font-size':14,fill:'#142635'},'off ['+outage.start+','+outage.end+')'));}for(const op of plan.schedule.filter(o=>o.machine===machine)){const x=left+op.start*scale,width=(op.end-op.start)*scale,r=svg('rect',{x,y,width,height:38,rx:4,fill:color(op.jobId),tabindex:0,'aria-label':op.id+' '+machine+' ['+op.start+','+op.end+') minutes'});r.append(svg('title',{},op.id+' ['+op.start+','+op.end+') · duration '+(op.end-op.start)+' minutes'));chart.append(r,svg('text',{x:x+width/2,y:y+25,'text-anchor':'middle','font-size':14,fill:Object.hasOwn(JOB_TEXT_COLORS,op.jobId)?JOB_TEXT_COLORS[op.jobId]:'#ffffff','pointer-events':'none'},op.id));}}
 for(const job of data.jobs.filter(j=>j.deadline!==undefined)){const x=left+job.deadline*scale,rightEdge=job.deadline>=horizon-3;chart.append(svg('line',{x1:x,y1:28,x2:x,y2:195,stroke:'#765091','stroke-dasharray':'5 3'}),svg('text',{x:x+(rightEdge?-4:4),y:218,'text-anchor':rightEdge?'end':'start','font-size':14,fill:'#765091'},job.id+' deadline '+job.deadline));}let x=left;for(const job of data.jobs){chart.append(svg('rect',{x,y:237,width:14,height:14,rx:2,fill:color(job.id)}),svg('text',{x:x+20,y:249,'font-size':14,fill:'#142635'},job.id));x+=Math.max(75,job.id.length*8+40);}chart.append(svg('text',{x:w-right,y:249,'text-anchor':'end','font-size':14,fill:'#142635'},'origin 0 · [start,end)'));root.append(chart);}
function operationTable(target,plan){const root=$(target);root.replaceChildren();if(!plan?.schedule?.length)return;const details=n('details');details.open=true;details.append(n('summary','작업 원장 · 정확한 시작 / 종료'));const table=n('table'),head=n('tr');for(const h of ['작업','설비','시작','종료','소요'])head.append(n('th',h));table.append(head);for(const op of plan.schedule){const row=n('tr');for(const value of [op.id,op.machine,op.start,op.end,op.end-op.start])row.append(n('td',value));table.append(row);}details.append(table);root.append(details);}
function decision(){const allowed=state?.proposal?.validation.valid&&$('convention').checked&&!mutationPending;$('confirm').disabled=!allowed;$('reject').disabled=!state?.proposal||mutationPending;$('review-plan').disabled=!state?.planFingerprint||state.plannedProposalId!==state.proposal?.id||!state.proposal?.validation.valid||mutationPending;}
function render(){
 $('source-info').textContent=(state.source.kind==='user-input'?'사용자 입력':'가상 예제')+' · '+state.base.id+' · 원본 revision '+state.sourceRevision+' · SHA256 '+state.sourceFingerprint+(state.source.inputFingerprint?' · 입력 SHA256 '+state.source.inputFingerprint:'');if(!$('baseline-json').dataset.initialized){$('baseline-json').value=JSON.stringify(state.base,null,2);$('baseline-json').dataset.initialized='true';}
 const p=state.proposal;if(p?.id!==previousProposal){$('convention').checked=false;previousProposal=p?.id;}
 $('proposal').replaceChildren();if(!p)$('proposal').append(n('p','수동 입력 또는 문장 해석으로 제안을 준비하세요. 확인 후 계획을 계산합니다.'));else{const status=p.validation.status==='STALE'?(p.status==='ARCHIVE_REJECTED'?'STALE / ARCHIVE_REJECTED':'STALE'):['ARCHIVE_REJECTED','MODEL_UNAVAILABLE'].includes(p.status)?p.status:p.validation.valid?p.status:p.validation.status;$('proposal').append(n('div',status+' · '+p.method,'proposal-status'),n('p','Source SHA256 '+p.sourceFingerprint,'fingerprint'));if(typeof p.sourceText==='string'&&p.sourceText)$('proposal').append(n('div','원문: '+p.sourceText,'quote'));if(p.archivedProposal){const details=n('details');details.open=true;const raw=n('pre',JSON.stringify(p.archivedProposal,null,2));raw.tabIndex=0;raw.setAttribute('aria-label','Untrusted original model proposal');details.append(n('summary','Rejected archive · original proposal (untrusted data)'),raw);$('proposal').append(details);}for(const c of p.changes||[]){const text=c.type==='add_outage'?'+ '+c.machine+' unavailable ['+c.start+','+c.end+') minutes':'+ '+c.id+' · '+c.operations.map(o=>o.id+'='+o.machine+'/'+o.duration+'m').join(' → ')+' · hard finish ≤ '+c.deadline+'m';$('proposal').append(n('div',text,'diff'),n('div','정확한 구절 ['+c.phrase.start+':'+c.phrase.end+']: '+c.phrase.text,'quote'));}for(const issue of [...(p.issues||[]),...(p.unsupportedClauses||[]).map(c=>c.reason),...(!p.validation.valid?p.validation.issues:[])])$('proposal').append(n('div',issue,'warning'));}
 const changed=state.changedPlan;
 $('result-evidence').textContent=JSON.stringify({displayedPlan:changed?(state.planIsCurrent?'CURRENT':'PREVIOUS_CONFIRMED_PLAN'):'BASELINE_ONLY',proposalId:state.plannedProposalId,planFingerprint:state.planFingerprint,solver:{status:(changed||state.baseline).status,proof:(changed||state.baseline).proof},independentVerifier:changed?state.changedVerification:state.baselineVerification,humanReview:state.receiptCompatibility},null,2);
 $('result-status').textContent='Solver '+(changed||state.baseline).status+' · 종료 '+(changed||state.baseline).proof.termination+' / 독립 verifier '+(changed?state.changedVerification:state.baselineVerification).status+' / 사람 검토 '+(!state.latestReceipt?'미기록':state.receiptCompatibility.current?'현재 계획 영수증':'이전 / 과거 영수증');
 const delta=changed?.makespan===undefined||state.baseline.makespan===undefined?null:changed.makespan-state.baseline.makespan;
 $('metrics').replaceChildren(...[['기준 완료시간',state.baseline.makespan===undefined?'—':state.baseline.makespan+'m'],[changed&&!state.planIsCurrent?'이전 계획 완료시간':'확인된 완료시간',changed?.makespan===undefined?'—':changed.makespan+'m'],['완료시간 차이',delta===null?'—':(delta>=0?'+':'')+delta+'m'],['증명된 하한',changed?.lowerBound===undefined?state.baseline.lowerBound===undefined?'—':state.baseline.lowerBound+'m':changed.lowerBound+'m']].map(([label,value])=>{const e=n('div',undefined,'metric');e.append(n('b',value),n('span',label));return e;}));
 $('changed-title').textContent=changed?(state.planIsCurrent?'확인된 시나리오':'이전 확인 계획 · 현재 제안 미확인')+' · proposal '+state.plannedProposalId.slice(0,8):'확인된 시나리오';$('displayed-plan-source').textContent=state.plannedProposal?'이 계획의 원문: '+state.plannedProposal.sourceText:'';$('displayed-plan-source').hidden=!state.plannedProposal;
 $('baseline-status').textContent=state.baseline.status+' · verifier '+state.baselineVerification.status;$('changed-status').textContent=changed?changed.status+' · verifier '+state.changedVerification.status:'미계산 · 해석 확인 필요';
 const horizon=sharedHorizon(state.base,state.baseline,state.changed,changed);$('baseline-axis').textContent=$('changed-axis').textContent='공통 축: 0–'+horizon+'분 · 가로 스크롤로 이후 구간 확인';gantt('baseline-chart',state.base,state.baseline,horizon);gantt('changed-chart',state.changed,changed,horizon);operationTable('baseline-table',state.baseline);operationTable('changed-table',changed);
 $('constraints').replaceChildren(...['M1 / M2 fixed exclusive machines · all releases 0','Positive integer durations · non-preemptive · [start,end)','Objective: minimize makespan',...state.base.jobs.map(j=>j.id+': '+j.operations.map(o=>o.id+'='+o.machine+'/'+o.duration+'m').join(' → ')),...(state.changed||state.base).outages.map(o=>'Unavailable '+o.machine+' ['+o.start+','+o.end+') minutes'),...(state.changed?.jobs||state.base.jobs).filter(j=>j.deadline!==undefined).map(j=>j.id+' hard completion deadline: '+j.deadline+'m'),...(changed?['Solver '+changed.status+' · '+changed.proof.enumerated+'/'+changed.proof.totalSequences+' sequences · '+changed.proof.termination,'Verifier '+state.changedVerification.status+' · '+(state.changedVerification.issues.join('; ')||'all independent checks passed')]:[])].map(t=>n('li',t)));
 $('history').replaceChildren(...state.history.slice(-7).map(h=>n('li',h.event.replaceAll('_',' ')+' · '+(h.solverStatus||h.status||h.id?.slice(0,8)||'new source'))));$('plan-hash').textContent=state.planFingerprint?(state.planIsCurrent?'Current':'Previous')+' plan SHA256 '+state.planFingerprint:'';$('receipt').hidden=!state.latestReceipt;$('receipt').textContent=state.receiptCompatibility.current?'로컬 검토 영수증 다운로드':'이전 / 과거 영수증 다운로드 · proposal '+state.latestReceipt?.proposal.id.slice(0,8);$('receipt-hash').textContent=state.latestReceipt?(state.receiptCompatibility.current?'Local':'Previous / historical')+' receipt for proposal '+state.latestReceipt.proposal.id.slice(0,8)+' · SHA256 '+state.latestReceipt.hash+' · '+state.receiptCompatibility.reason+' · no production release':'';decision();
}
function fields(){const job=$('change').value==='add_job';$('job-fields').hidden=!job;$('outage-fields').hidden=job;}
$('load-baseline').onclick=()=>{$('baseline-json').value=JSON.stringify(state.base,null,2);};$('import-baseline').onclick=()=>{try{const text=$('baseline-json').value;if(new TextEncoder().encode(text).length>12000)throw Error('기준 JSON은 12,000 bytes 이하로 입력하세요.');request('import',{baseline:JSON.parse(text)});}catch(e){$('status').textContent=e.message;$('import-status').textContent=e.message;}};
$('change').onchange=fields;$('convention').onchange=decision;
$('preset-b').onclick=()=>{$('change').value='add_outage';$('machine').value='M1';$('start').value=2;$('end').value=4;fields();};$('preset-c').onclick=()=>{$('change').value='add_job';$('job-id').value='J4';$('operation1').value='J4A';$('operation2').value='J4B';$('machine1').value='M2';$('machine2').value='M1';$('duration1').value=1;$('duration2').value=1;$('deadline').value=4;fields();};
$('manual').onclick=()=>request('propose',{method:'manual',input:$('change').value==='add_outage'?{type:'add_outage',machine:$('machine').value,start:$('start').value,end:$('end').value}:{type:'add_job',id:$('job-id').value,operation1:$('operation1').value,operation2:$('operation2').value,machine1:$('machine1').value,machine2:$('machine2').value,duration1:$('duration1').value,duration2:$('duration2').value,deadline:$('deadline').value}});
$('interpret').onclick=()=>request('propose',{method:'rule',text:$('request').value});$('recorded').onclick=()=>request('propose',{method:'recorded',caseId:$('case').value});
$('confirm').onclick=()=>request('confirm',{proposalId:state.proposal.id,proposalHash:state.proposal.proposalHash,sourceFingerprint:state.proposal.sourceFingerprint,confirmConvention:$('convention').checked,budget:$('budget').value});$('review-plan').onclick=()=>request('review',{proposalId:state.proposal.id,proposalHash:state.proposal.proposalHash,sourceFingerprint:state.sourceFingerprint,planFingerprint:state.planFingerprint});$('reject').onclick=()=>request('reject',{});$('calendar').onclick=()=>request('calendar',{});$('reset').onclick=()=>request('reset',{});request('state');
