const $=id=>document.getElementById(id),n=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
let state=null,generation=0,mutationPending=false,previousProposal=null;
function setBusy(busy){for(const button of document.querySelectorAll('button'))button.disabled=busy;$('status').textContent=busy?'Working · waiting for the local review response…':'';if(!busy)decision();}
async function request(path,input){if(input&&mutationPending)return;const current=++generation;if(input)mutationPending=true;setBusy(true);try{const response=await fetch('/api/'+path,input?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}:{});const result=await response.json();if(current!==generation)return;if(!response.ok)throw Error((result.message||result.error)+' · inspect again before confirming');if(state&&result.version<state.version)return;state=result;$('status').textContent='';render();}catch(e){if(current===generation)$('status').textContent=e.message;}finally{if(input)mutationPending=false;if(current===generation){for(const button of document.querySelectorAll('button'))button.disabled=false;decision();}}}
const color=id=>({J1:'#4973a7',J2:'#338c7b',J3:'#b9963d',J4:'#8d68a8'})[id]||'#677d7d';
const svg=(tag,attrs,text)=>{const e=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v]of Object.entries(attrs||{}))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;return e;};
function gantt(target,data,plan,horizon){const root=$(target);root.replaceChildren();if(!plan?.schedule?.length){root.append(n('div',plan?'No feasible incumbent · '+plan.status:'Confirm a supported interpretation to plan','empty'));return;}const w=560,left=48,right=18,scale=(w-left-right)/horizon;const chart=svg('svg',{viewBox:'0 0 560 220',role:'img','aria-label':'Machine schedule in integer minutes. Half-open intervals.'});
 for(let minute=0;minute<=horizon;minute++){const x=left+minute*scale;chart.append(svg('line',{x1:x,y1:28,x2:x,y2:177,stroke:'#e1e7dd'}),svg('text',{x,y:20,'text-anchor':'middle','font-size':11,fill:'#728574'},String(minute)));}
 for(const [i,machine]of data.machines.entries()){const y=55+i*66;chart.append(svg('text',{x:5,y:y+21,'font-size':12,fill:'#375953'},machine),svg('line',{x1:left,y1:y+40,x2:w-right,y2:y+40,stroke:'#d5ded3'}));for(const outage of data.outages.filter(o=>o.machine===machine)){const r=svg('rect',{x:left+outage.start*scale,y:y-7,width:(outage.end-outage.start)*scale,height:51,fill:'#dadbd2',stroke:'#8c9385','stroke-dasharray':'3 3'});r.append(svg('title',{},'Unavailable '+machine+' ['+outage.start+','+outage.end+')'));chart.append(r,svg('text',{x:left+(outage.start+outage.end)*scale/2,y:y+55,'text-anchor':'middle','font-size':10,fill:'#53604e'},'off ['+outage.start+','+outage.end+')'));}for(const op of plan.schedule.filter(o=>o.machine===machine)){const x=left+op.start*scale,width=(op.end-op.start)*scale,r=svg('rect',{x,y,width,height:34,rx:4,fill:color(op.jobId),tabindex:0,'aria-label':op.id+' '+machine+' ['+op.start+','+op.end+') minutes'});r.append(svg('title',{},op.id+' ['+op.start+','+op.end+') · duration '+(op.end-op.start)+' minutes'));chart.append(r,svg('text',{x:x+width/2,y:y+21,'text-anchor':'middle','font-size':11,fill:'white','pointer-events':'none'},op.id));}}
 for(const job of data.jobs.filter(j=>j.deadline!==undefined)){const x=left+job.deadline*scale;chart.append(svg('line',{x1:x,y1:28,x2:x,y2:177,stroke:'#8d68a8','stroke-dasharray':'5 3'}),svg('text',{x:x+3,y:190,'font-size':10,fill:'#8d68a8'},job.id+' deadline '+job.deadline));} let x=left;for(const job of data.jobs){chart.append(svg('rect',{x,y:198,width:11,height:11,rx:2,fill:color(job.id)}),svg('text',{x:x+16,y:207,'font-size':10,fill:'#597565'},job.id));x+=72;}chart.append(svg('text',{x:w-right,y:207,'text-anchor':'end','font-size':10,fill:'#597565'},'origin 0 · [start,end)'));root.append(chart);}
function operationTable(target,plan){const root=$(target);root.replaceChildren();if(!plan?.schedule?.length)return;const details=n('details');details.append(n('summary','Accessible operation ledger · exact intervals'));const table=n('table'),head=n('tr');for(const h of ['Operation','Machine','Start','End','Duration'])head.append(n('th',h));table.append(head);for(const op of plan.schedule){const row=n('tr');for(const value of [op.id,op.machine,op.start,op.end,op.end-op.start])row.append(n('td',value));table.append(row);}details.append(table);root.append(details);}
function decision(){const allowed=state?.proposal?.validation.valid&&$('convention').checked&&!mutationPending;$('confirm').disabled=!allowed;$('reject').disabled=!state?.proposal||mutationPending;$('review-plan').disabled=!state?.planFingerprint||state.plannedProposalId!==state.proposal?.id||!state.proposal?.validation.valid||mutationPending;}
function render(){
 const p=state.proposal;if(p?.id!==previousProposal){$('convention').checked=false;previousProposal=p?.id;}
 $('proposal').replaceChildren();if(!p)$('proposal').append(n('p','Prepare a manual or language interpretation. Planning starts after confirmation.'));else{const status=['ARCHIVE_REJECTED','MODEL_UNAVAILABLE'].includes(p.status)?p.status:p.validation.valid?p.status:p.validation.status;$('proposal').append(n('div',status+' · '+p.method,'proposal-status'),n('p','Source SHA256 '+p.sourceFingerprint,'fingerprint'));if(typeof p.sourceText==='string'&&p.sourceText)$('proposal').append(n('div','Original request: '+p.sourceText,'quote'));if(p.archivedProposal){const details=n('details');const raw=n('pre',JSON.stringify(p.archivedProposal,null,2));raw.tabIndex=0;raw.setAttribute('aria-label','Untrusted original model proposal');details.append(n('summary','Rejected archive · original proposal (untrusted data)'),raw);$('proposal').append(details);}for(const c of p.changes||[]){const text=c.type==='add_outage'?'+ '+c.machine+' unavailable ['+c.start+','+c.end+') minutes':'+ '+c.id+' · '+c.operations.map(o=>o.id+'='+o.machine+'/'+o.duration+'m').join(' → ')+' · hard finish ≤ '+c.deadline+'m';$('proposal').append(n('div',text,'diff'),n('div','Exact phrase ['+c.phrase.start+':'+c.phrase.end+']: '+c.phrase.text,'quote'));}for(const issue of [...(p.issues||[]),...(p.unsupportedClauses||[]).map(c=>c.reason),...(!p.validation.valid?p.validation.issues:[])])$('proposal').append(n('div',issue,'warning'));}
 const changed=state.changedPlan;const delta=changed?.makespan===undefined?null:changed.makespan-state.baseline.makespan;
 $('metrics').replaceChildren(...[['Baseline makespan',state.baseline.makespan+'m'],['Confirmed makespan',changed?.makespan===undefined?'—':changed.makespan+'m'],['Numeric delta',delta===null?'—':(delta>=0?'+':'')+delta+'m'],['Proven lower bound',changed?.lowerBound===undefined?state.baseline.lowerBound+'m':changed.lowerBound+'m']].map(([label,value])=>{const e=n('div',undefined,'metric');e.append(n('b',value),n('span',label));return e;}));
 $('baseline-status').textContent=state.baseline.status+' · verifier '+state.baselineVerification.status;$('changed-status').textContent=changed?changed.status+' · verifier '+state.changedVerification.status:'Not planned';
 const horizon=Math.max(10,state.baseline.makespan||0,changed?.makespan||0,...state.base.outages.map(o=>o.end),...(state.changed?.outages||[]).map(o=>o.end));gantt('baseline-chart',state.base,state.baseline,horizon);gantt('changed-chart',state.changed,changed,horizon);operationTable('baseline-table',state.baseline);operationTable('changed-table',changed);
 $('constraints').replaceChildren(...['M1 / M2 fixed exclusive machines · all releases 0','Positive integer durations · non-preemptive · [start,end)','Objective: minimize makespan',...state.base.jobs.map(j=>j.id+': '+j.operations.map(o=>o.id+'='+o.machine+'/'+o.duration+'m').join(' → ')),...(state.changed||state.base).outages.map(o=>'Unavailable '+o.machine+' ['+o.start+','+o.end+') minutes'),...(state.changed?.jobs||[]).filter(j=>j.deadline!==undefined).map(j=>j.id+' hard completion deadline: '+j.deadline+'m'),...(changed?['Solver '+changed.status+' · '+changed.proof.enumerated+'/'+changed.proof.totalSequences+' sequences · '+changed.proof.termination,'Verifier '+state.changedVerification.status+' · '+(state.changedVerification.issues.join('; ')||'all independent checks passed')]:[])].map(t=>n('li',t)));
 $('history').replaceChildren(...state.history.slice(-7).map(h=>n('li',h.event.replaceAll('_',' ')+' · '+(h.solverStatus||h.status||h.id?.slice(0,8)||'new source'))));$('plan-hash').textContent=state.planFingerprint?'Inspected plan SHA256 '+state.planFingerprint:'';$('receipt').hidden=!state.latestReceipt;$('receipt').textContent=state.receiptCompatibility.current?'Download local review receipt':'Download historical receipt · source changed';$('receipt-hash').textContent=state.latestReceipt?(state.receiptCompatibility.current?'Local':'Historical / incompatible')+' receipt SHA256 '+state.latestReceipt.hash+' · '+state.receiptCompatibility.reason+' · no production release':'';decision();
}
function fields(){const job=$('change').value==='add_job';$('job-fields').hidden=!job;$('outage-fields').hidden=job;}
$('change').onchange=fields;$('convention').onchange=decision;
$('preset-b').onclick=()=>{$('change').value='add_outage';$('machine').value='M1';$('start').value=2;$('end').value=4;fields();};$('preset-c').onclick=()=>{$('change').value='add_job';$('machine1').value='M2';$('machine2').value='M1';$('duration1').value=1;$('duration2').value=1;$('deadline').value=4;fields();};
$('manual').onclick=()=>request('propose',{method:'manual',input:$('change').value==='add_outage'?{type:'add_outage',machine:$('machine').value,start:$('start').value,end:$('end').value}:{type:'add_job',machine1:$('machine1').value,machine2:$('machine2').value,duration1:$('duration1').value,duration2:$('duration2').value,deadline:$('deadline').value}});
$('interpret').onclick=()=>request('propose',{method:'rule',text:$('request').value});$('recorded').onclick=()=>request('propose',{method:'recorded',caseId:$('case').value});
$('confirm').onclick=()=>request('confirm',{proposalId:state.proposal.id,proposalHash:state.proposal.proposalHash,sourceFingerprint:state.proposal.sourceFingerprint,confirmConvention:$('convention').checked,budget:$('budget').value});$('review-plan').onclick=()=>request('review',{proposalId:state.proposal.id,proposalHash:state.proposal.proposalHash,sourceFingerprint:state.sourceFingerprint,planFingerprint:state.planFingerprint});$('reject').onclick=()=>request('reject',{});$('calendar').onclick=()=>request('calendar',{});$('reset').onclick=()=>request('reset',{});request('state');
