import asyncio,json
from pathlib import Path
from playwright.async_api import async_playwright,expect
ROOT=Path(__file__).resolve().parent
async def state(page):return await page.evaluate("fetch('/api/state').then(r=>r.json())")
async def prepare_b(page):
    await page.locator('#preset-b').click();await page.locator('#manual').click();await expect(page.locator('#proposal .diff')).to_contain_text('M1 unavailable');await page.locator('#convention').check();await expect(page.locator('#confirm')).to_be_enabled();await page.locator('#confirm').click();await expect(page.locator('#metrics')).to_contain_text('9m')
async def main():
    results={'browser':'actual installed Google Chrome via Playwright','modelCalls':0}
    async with async_playwright() as p:
        browser=await p.chromium.launch(executable_path='/usr/bin/google-chrome',headless=True,args=['--no-sandbox','--disable-gpu']);page=await browser.new_page(viewport={'width':1440,'height':1100});await page.goto('http://127.0.0.1:5077');await page.wait_for_selector('#baseline-chart svg');await page.locator('#reset').click();await prepare_b(page);await page.locator('#review-plan').click();await expect(page.locator('#receipt')).to_be_visible();old=await state(page);await page.screenshot(path=str(ROOT/'artifacts/media/readable-outage-reviewed.png'),full_page=True)
        await page.locator('#preset-c').click();await page.locator('#manual').click();await expect(page.locator('#proposal .diff')).to_contain_text('J4A');await expect(page.locator('#changed-title')).to_contain_text('Previous confirmed plan');await expect(page.locator('#metrics')).to_contain_text('Previous plan makespan');assert await page.locator('#review-plan').is_disabled();assert 'previous' in (await page.locator('#receipt').inner_text()).lower();assert await page.locator('#confirm').is_disabled()
        pending=await state(page);assert pending['changedPlan']['makespan']==9 and pending['planIsCurrent'] is False;assert pending['plannedProposal']['id']==old['proposal']['id'];assert pending['latestReceipt']['hash']==old['latestReceipt']['hash'] and pending['receiptCompatibility']['current'] is False;assert pending['proposal']['id']!=pending['plannedProposal']['id'];assert old['proposal']['sourceText'] in await page.locator('#displayed-plan-source').inner_text();await page.locator('#displayed-plan-source').focus();assert await page.locator('#displayed-plan-source').evaluate('(n)=>n===document.activeElement');await page.screenshot(path=str(ROOT/'artifacts/media/plan-binding-fixed.png'),full_page=True)
        results['planBinding']={'previousMakespan':9,'previousProposalId':pending['plannedProposalId'],'newProposalId':pending['proposal']['id'],'receiptHashPreserved':True,'receiptCurrent':False,'previousLabelVisible':True,'exactPlanSourceKeyboardFocusable':True}
        await page.locator('#deadline').fill('30');await page.locator('#manual').click();await expect(page.locator('#proposal .diff')).to_contain_text('30m');await page.locator('#convention').check();await expect(page.locator('#confirm')).to_be_enabled();await page.locator('#confirm').click();await expect(page.locator('#changed-chart svg')).to_contain_text('J4 deadline 30')
        axes=await page.locator('.gantt-scroll svg').evaluate_all('(nodes)=>nodes.map(n=>({viewBox:n.getAttribute("viewBox"),width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height,ticks:[...n.querySelectorAll("text")].filter(t=>/^\\d+$/.test(t.textContent)).map(t=>t.textContent)}))');assert axes[0]==axes[1];assert axes[0]['width']>=1206
        marker=await page.locator('#changed-chart svg line[stroke="#765091"]').evaluate('(n)=>({x:Number(n.getAttribute("x1")),viewBoxWidth:n.ownerSVGElement.viewBox.baseVal.width})');assert 0<=marker['x']<=marker['viewBoxWidth'];await page.locator('#changed-chart').evaluate('(n)=>n.scrollLeft=n.scrollWidth');await page.screenshot(path=str(ROOT/'artifacts/media/deadline-axis-fixed.png'),full_page=True);results['deadlineAxis']={'deadline':30,'bothAxes':axes,'marker':marker,'nativeHorizontalScroll':True}
        await page.locator('#reset').click();await prepare_b(page);await page.locator('#budget').select_option('limited');await page.locator('#confirm').click();await expect(page.locator('#changed-status')).to_contain_text('UNKNOWN');await page.screenshot(path=str(ROOT/'artifacts/media/readable-unknown-desktop.png'),full_page=True)
        mobile=await browser.new_page(viewport={'width':390,'height':1000});await mobile.goto('http://127.0.0.1:5077');await mobile.wait_for_selector('#baseline-chart svg');await mobile.screenshot(path=str(ROOT/'artifacts/media/readable-unknown-390.png'),full_page=True);assert await mobile.evaluate('document.documentElement.scrollWidth')==390
        font_facts=await mobile.evaluate('''()=>{const elements=[...document.querySelectorAll('body *')].filter(n=>n.getBoundingClientRect().width&&n.getBoundingClientRect().height&&(n.textContent?.trim()||['INPUT','SELECT','TEXTAREA'].includes(n.tagName)));const sizes=elements.map(n=>Number.parseFloat(getComputedStyle(n).fontSize));return {minimumTextPixels:Math.min(...sizes),metricLabelPixels:getComputedStyle(document.querySelector('.metric span')).fontSize,hashPixels:getComputedStyle(document.getElementById('plan-hash')).fontSize,axisPixels:getComputedStyle(document.querySelector('svg text')).fontSize};}''');assert font_facts['minimumTextPixels']>=14
        colors=await mobile.evaluate('''()=>{const pairs=[];const axis=document.querySelector('svg text');pairs.push({name:'axis',fg:getComputedStyle(axis).fill,bg:getComputedStyle(document.querySelector('article')).backgroundColor});const metric=document.querySelector('.metric span');pairs.push({name:'metric label',fg:getComputedStyle(metric).color,bg:getComputedStyle(metric.parentElement).backgroundColor});for(const rect of document.querySelectorAll('#baseline-chart rect[tabindex]'))pairs.push({name:rect.getAttribute('aria-label').split(' ')[0],fg:getComputedStyle(rect.nextElementSibling).fill,bg:getComputedStyle(rect).fill});return pairs;}''')
        def lum(c):
            rgb=[int(x.strip())/255 for x in c.removeprefix('rgb(').removesuffix(')').split(',')];v=[x/12.92 if x<=.04045 else ((x+.055)/1.055)**2.4 for x in rgb];return .2126*v[0]+.7152*v[1]+.0722*v[2]
        for pair in colors:a,b=lum(pair['fg']),lum(pair['bg']);pair['ratio']=(max(a,b)+.05)/(min(a,b)+.05);assert pair['ratio']>=4.5
        results['readability']={'mobileWidth':390,'documentWidth':390,'fonts':font_facts,'declaredComputedColorPairs':colors,'normalTextTarget':4.5,'fullWcagAudit':False,'chartShrunk':False}
        await mobile.locator('#calendar').click();await expect(mobile.locator('#proposal')).to_contain_text('STALE');await mobile.screenshot(path=str(ROOT/'artifacts/media/readable-stale-390.png'),full_page=True);assert await mobile.locator('#confirm').is_disabled();await browser.close()
    (ROOT/'artifacts/ui-boundary-fixed.json').write_text(json.dumps(results,indent=2)+'\n');print(json.dumps(results))
if __name__=='__main__':asyncio.run(main())
